// ─── 教授 Professors ─────────────────────────────────────────
const PROFESSORS = [
  {
    id: 'p1',
    full_name: '陳錫民 教授',
    department_id: 'd1',
    email: 'hsiminc@fcu.edu.tw',
    title: '教授兼系主任',
    research: '軟體工程、DevOps、分散式系統',
    bio: '專長於軟體工程與分散式運算，課程重視實作與團隊合作，強調業界開發流程與系統架構設計。',
    photo_initials: '陳',
  },
  {
    id: 'p2',
    full_name: '薛念林 教授',
    department_id: 'd1',
    email: 'nlhsueh@fcu.edu.tw',
    title: '教授',
    research: '軟體工程、軟體測試、物件導向設計',
    bio: '長期投入軟體工程教育與系統設計研究，教學內容扎實，深受學生喜愛。',
    photo_initials: '薛',
  },
  {
    id: 'p3',
    full_name: '李榮三 特聘教授',
    department_id: 'd1',
    email: 'leejs@fcu.edu.tw',
    title: '特聘教授',
    research: '資訊安全、區塊鏈、無線通訊',
    bio: '研究方向涵蓋資訊安全與區塊鏈技術，課程偏向實務與新興科技應用。',
    photo_initials: '李',
  },
  {
    id: 'p4',
    full_name: '林志敏 教授',
    department_id: 'd1',
    email: 'jimmy@fcu.edu.tw',
    title: '教授',
    research: '嵌入式系統、作業系統、機器人',
    bio: '擅長作業系統與嵌入式開發，課堂中經常加入實作專題與硬體應用。',
    photo_initials: '林',
  },
  {
    id: 'p5',
    full_name: '許芳榮 教授',
    department_id: 'd1',
    email: 'frhsu@o365.fcu.edu.tw',
    title: '教授',
    research: '人工智慧、雲端運算、生物資訊',
    bio: '研究 AI 與雲端技術整合，課程內容結合理論與 AI 應用實作。',
    photo_initials: '許',
  },
  {
    id: 'p6',
    full_name: '黃秀芬 教授',
    department_id: 'd1',
    email: 'sfhwang@mail.fcu.edu.tw',
    title: '教授',
    research: '演算法、圖論、無線感測網路',
    bio: '專注於演算法與網路相關研究，授課邏輯清楚且重視基礎能力。',
    photo_initials: '黃',
  },
];